<template>
  <div class="admin-page admin-account-page" v-loading="loading">
    <div class="admin-page__header"><div><h2>管理员账号</h2><p class="admin-page__description">维护管理员登录安全并查看近期敏感操作</p></div><el-button type="primary" :icon="Lock" @click="openPasswordDialog">修改密码</el-button></div>
    <div class="admin-account-grid">
      <section class="admin-panel admin-profile-card"><div class="admin-profile-card__cover"></div><div class="admin-profile-card__body"><div class="admin-profile-card__avatar"><el-icon><UserFilled/></el-icon></div><h3>{{profile.displayName||'管理员'}}</h3><p>@{{profile.username||'-'}}</p><el-tag type="primary">超级管理员</el-tag><div class="admin-profile-facts"><div><span><el-icon><Clock/></el-icon>最后登录</span><strong>{{profile.lastLoginTime||'暂无记录'}}</strong></div><div><span><el-icon><Lock/></el-icon>账号状态</span><strong class="admin-text-success">正常</strong></div><div><span><el-icon><Key/></el-icon>安全建议</span><strong>定期更换高强度密码</strong></div></div></div></section>
      <section class="admin-panel admin-security-card"><div class="admin-panel-toolbar"><div><strong>账号安全</strong><span>保护管理员账号和平台数据</span></div><span class="admin-security-score">安全</span></div><div class="admin-security-list"><div><span class="admin-security-list__icon admin-security-list__icon--green"><el-icon><CircleCheck/></el-icon></span><div><strong>登录密码</strong><p>当前密码已设置，建议至少使用 10 位混合字符</p></div><el-button @click="openPasswordDialog">修改</el-button></div><div><span class="admin-security-list__icon admin-security-list__icon--blue"><el-icon><DocumentChecked/></el-icon></span><div><strong>操作审计</strong><p>敏感操作会自动记录管理员、目标和操作原因</p></div><el-tag type="success">已启用</el-tag></div><div><span class="admin-security-list__icon admin-security-list__icon--orange"><el-icon><Warning/></el-icon></span><div><strong>账号使用规范</strong><p>请勿共享管理员账号，离开电脑前及时退出登录</p></div></div></div></section>
      <section class="admin-panel admin-audit-card"><div class="admin-panel-toolbar"><div><strong>近期操作记录</strong><span>最近 100 条管理员操作日志</span></div><el-button :icon="Refresh" circle title="刷新" @click="load"/></div><el-table :data="logs" max-height="520"><el-table-column prop="createTime" label="操作时间" width="170"/><el-table-column label="操作类型" width="180"><template #default="scope"><el-tag effect="plain">{{operationLabel(scope.row.operationType)}}</el-tag></template></el-table-column><el-table-column label="操作目标" width="150"><template #default="scope">{{scope.row.targetType}} #{{scope.row.targetId}}</template></el-table-column><el-table-column prop="reason" label="操作说明" show-overflow-tooltip/><el-table-column prop="ipAddress" label="IP 地址" width="130"/></el-table><div v-if="!logs.length" class="admin-empty">暂无操作记录</div></section>
    </div>
    <el-dialog v-model="passwordDialog" title="修改登录密码" width="500px" destroy-on-close><el-alert title="新密码至少 10 位，建议包含大小写字母、数字和符号。" type="info" :closable="false" show-icon/><el-form label-position="top" class="admin-dialog-form"><el-form-item label="当前密码"><el-input v-model="password.oldPassword" type="password" show-password autocomplete="current-password"/></el-form-item><el-form-item label="新密码"><el-input v-model="password.newPassword" type="password" show-password autocomplete="new-password"/></el-form-item><el-form-item label="确认新密码"><el-input v-model="confirmPassword" type="password" show-password autocomplete="new-password"/></el-form-item></el-form><template #footer><el-button @click="passwordDialog=false">取消</el-button><el-button type="primary" :loading="changingPassword" @click="changePassword">确认修改</el-button></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { CircleCheck, Clock, DocumentChecked, Key, Lock, Refresh, UserFilled, Warning } from '@element-plus/icons-vue';
import { ElMessage } from 'element-plus';
import request from '@/utils/request';
import './admin.css';
const profile=reactive<any>({}),logs=ref<any[]>([]),loading=ref(false),passwordDialog=ref(false),changingPassword=ref(false),confirmPassword=ref('');const password=reactive({oldPassword:'',newPassword:''});
const load=async()=>{loading.value=true;try{const[profileData,logData]:any=await Promise.all([request.get('/api/admin/auth/profile'),request.get('/api/admin/audit-logs')]);Object.assign(profile,profileData);logs.value=logData}finally{loading.value=false}};
const openPasswordDialog=()=>{password.oldPassword='';password.newPassword='';confirmPassword.value='';passwordDialog.value=true};
const changePassword=async()=>{if(password.newPassword.length<10)return ElMessage.warning('新密码至少 10 位');if(password.newPassword!==confirmPassword.value)return ElMessage.warning('两次输入的新密码不一致');changingPassword.value=true;try{await request.put('/api/admin/auth/password',password);ElMessage.success('密码修改成功');passwordDialog.value=false}finally{changingPassword.value=false}};
const operationLabel=(value:string)=>({CREATE_SHOP:'新增商户',UPDATE_SHOP:'修改商户',RESET_SHOP_PASSWORD:'重置商户密码',CORRECT_ORDER_STATUS:'纠正订单状态',UPDATE_USER_PENALTY:'处理用户处罚',UPDATE_RESERVATION_CONFIG:'修改预约规则',UPDATE_LUCKY_DRAW_CONFIG:'修改抽奖配置',CREATE_CANTEEN:'新增食堂',UPDATE_CANTEEN:'修改食堂'}[value]||value);
onMounted(load);
</script>
