<template>
  <div class="admin-page admin-shops">
    <div class="admin-page__header"><div><h2>商户与食堂</h2><p class="admin-page__description">维护商户资料、展示信息和所属食堂</p></div><div class="admin-header-actions"><el-button :icon="Download" @click="exportCsv">导出商户</el-button><el-button type="primary" :icon="Plus" @click="openShopForm()">新增商户</el-button></div></div>
    <el-tabs v-model="tab" class="admin-section-tabs">
      <el-tab-pane label="商户管理" name="shops">
        <section class="admin-filter-panel"><div class="admin-filter-panel__top"><div class="admin-filter-panel__title"><el-icon><Filter /></el-icon>筛选商户</div><el-button link :icon="RefreshLeft" @click="resetShopFilter">重置</el-button></div><div class="admin-filter-grid"><label><span>商户搜索</span><el-input v-model="keyword" placeholder="商户 ID、名称或手机号" clearable @keyup.enter="searchShops"/></label><label><span>所属食堂</span><el-select v-model="canteenId" clearable placeholder="全部食堂"><el-option v-for="canteen in canteens" :key="canteen.id" :label="canteen.name" :value="canteen.id"/></el-select></label><div class="admin-filter-panel__inline-action"><el-button type="primary" :icon="Search" @click="searchShops">查询商户</el-button></div></div></section>
        <div class="admin-panel admin-table-panel"><el-table :data="shops" v-loading="loading"><el-table-column label="商户" min-width="210"><template #default="scope"><div class="admin-shop-cell"><el-image :src="scope.row.logo_image" fit="cover" class="admin-shop-logo"><template #error><div class="admin-image-fallback"><el-icon><Shop /></el-icon></div></template></el-image><div><strong>{{scope.row.name}}</strong><small>ID {{scope.row.id}} · {{scope.row.address||'未设置地址'}}</small></div></div></template></el-table-column><el-table-column prop="canteen_name" label="所属食堂" min-width="120"/><el-table-column prop="contact_phone" label="联系电话" width="135"/><el-table-column label="经营模式" width="110"><template #default="scope">{{scope.row.shop_mode==='weight_selection'?'自选称重':'固定菜品'}}</template></el-table-column><el-table-column label="营业" width="85"><template #default="scope"><el-tag :type="scope.row.status?'success':'info'">{{scope.row.status?'营业':'休息'}}</el-tag></template></el-table-column><el-table-column label="展示" width="85"><template #default="scope"><el-tag :type="scope.row.visible?'primary':'danger'">{{scope.row.visible?'显示':'隐藏'}}</el-tag></template></el-table-column><el-table-column prop="order_count" label="总订单" width="90"/><el-table-column label="操作" width="175" fixed="right"><template #default="scope"><el-button link type="primary" :icon="Edit" @click="openShopForm(scope.row)">编辑</el-button><el-button link type="danger" :icon="Key" @click="resetPassword(scope.row)">重置密码</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="page" :page-size="20" :total="total" layout="total,prev,pager,next" @current-change="loadShops" class="admin-pagination"/></div>
      </el-tab-pane>
      <el-tab-pane label="食堂管理" name="canteens"><div class="admin-panel admin-table-panel"><div class="admin-panel-toolbar"><div><strong>食堂列表</strong><span>用于归类商户并在客户端分组展示</span></div><el-button type="primary" :icon="Plus" @click="editCanteen()">新增食堂</el-button></div><el-table :data="canteens"><el-table-column prop="id" label="ID" width="90"/><el-table-column prop="name" label="食堂名称"/><el-table-column prop="sortOrder" label="展示排序" width="120"/><el-table-column label="状态" width="110"><template #default="scope"><el-tag :type="scope.row.status?'success':'info'">{{scope.row.status?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="100"><template #default="scope"><el-button link type="primary" :icon="Edit" @click="editCanteen(scope.row)">编辑</el-button></template></el-table-column></el-table></div></el-tab-pane>
    </el-tabs>

    <el-dialog v-model="shopDialog" :title="shopForm.id?'编辑商户':'新增商户'" width="820px" destroy-on-close class="admin-shop-dialog">
      <el-form :model="shopForm" label-position="top">
        <div class="admin-form-section"><div class="admin-form-section__title"><el-icon><Picture /></el-icon><div><strong>品牌图片</strong><span>用于小程序商户列表和商户详情展示</span></div></div><div class="admin-shop-images"><label><span>商户 Logo</span><el-upload :show-file-list="false" accept="image/*" :http-request="uploadLogo"><div class="admin-image-upload admin-image-upload--logo" v-loading="uploading.logo"><img v-if="shopForm.logoImage" :src="shopForm.logoImage"/><div v-else><el-icon><Plus /></el-icon><span>上传 Logo</span></div><i v-if="shopForm.logoImage">点击更换</i></div></el-upload><small>建议正方形，最大 5MB</small></label><label><span>店铺封面</span><el-upload :show-file-list="false" accept="image/*" :http-request="uploadCover"><div class="admin-image-upload admin-image-upload--cover" v-loading="uploading.cover"><img v-if="shopForm.coverImage" :src="shopForm.coverImage"/><div v-else><el-icon><Plus /></el-icon><span>上传封面</span></div><i v-if="shopForm.coverImage">点击更换</i></div></el-upload><small>建议横向图片，最大 5MB</small></label></div></div>
        <div class="admin-form-section"><div class="admin-form-section__title"><el-icon><Shop /></el-icon><div><strong>基础资料</strong><span>商户登录和线下联系所需信息</span></div></div><div class="admin-form-grid"><el-form-item label="商户名称" required><el-input v-model="shopForm.name" placeholder="请输入商户名称"/></el-form-item><el-form-item label="所属食堂" required><el-select v-model="shopForm.canteenId" style="width:100%"><el-option v-for="canteen in canteens" :key="canteen.id" :label="canteen.name" :value="canteen.id"/></el-select></el-form-item><el-form-item label="联系电话"><el-input v-model="shopForm.contactPhone" placeholder="商户登录手机号"/></el-form-item><el-form-item label="展示顺序"><el-input-number v-model="shopForm.displaySort" :min="0" style="width:100%"/></el-form-item><el-form-item label="取餐地址" class="admin-form-grid__full"><el-input v-model="shopForm.address" placeholder="例如：第二食堂一楼 5 号窗口"/></el-form-item></div></div>
        <div class="admin-form-section"><div class="admin-form-section__title"><el-icon><Clock /></el-icon><div><strong>营业与经营配置</strong><span>控制客户端状态和业务模式</span></div></div><div class="admin-form-grid"><el-form-item label="第一营业时段"><el-time-picker v-model="firstHours" is-range value-format="HH:mm:ss" range-separator="至" start-placeholder="开始" end-placeholder="结束" style="width:100%"/></el-form-item><el-form-item label="第二营业时段（可选）"><el-time-picker v-model="secondHours" is-range value-format="HH:mm:ss" range-separator="至" start-placeholder="开始" end-placeholder="结束" style="width:100%"/></el-form-item><el-form-item label="经营模式"><el-select v-model="shopForm.shopMode" style="width:100%"><el-option label="固定菜品" value="fixed_dish"/><el-option label="自选称重" value="weight_selection"/></el-select></el-form-item><el-form-item v-if="shopForm.shopMode==='weight_selection'" label="每 500g 价格"><el-input-number v-model="shopForm.weightPricePer500g" :min="0" :precision="2" style="width:100%"/></el-form-item><el-form-item v-if="shopForm.shopMode==='weight_selection'" label="最低下单重量(g)"><el-input-number v-model="shopForm.minimumOrderWeightG" :min="0" style="width:100%"/></el-form-item></div><div class="admin-switch-list"><label><div><strong>营业状态</strong><span>关闭后商户端显示休息</span></div><el-switch v-model="shopForm.status" :active-value="1" :inactive-value="0"/></label><label><div><strong>客户端展示</strong><span>关闭后用户端不再显示该商户</span></div><el-switch v-model="shopForm.visible" :active-value="1" :inactive-value="0"/></label><label><div><strong>高峰预约限制</strong><span>启用平台高峰期预约规则</span></div><el-switch v-model="shopForm.peakLimitEnabled" :active-value="1" :inactive-value="0"/></label><label><div><strong>口感敏感提醒</strong><span>订单中突出显示口感备注</span></div><el-switch v-model="shopForm.tasteSensitiveEnabled" :active-value="1" :inactive-value="0"/></label></div></div>
      </el-form>
      <template #footer><el-button @click="shopDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveShop">{{shopForm.id?'保存修改':'创建商户'}}</el-button></template>
    </el-dialog>

    <el-dialog v-model="canteenDialog" :title="canteenForm.id?'编辑食堂':'新增食堂'" width="480px"><el-form label-position="top"><el-form-item label="食堂名称"><el-input v-model="canteenForm.name"/></el-form-item><el-form-item label="展示排序"><el-input-number v-model="canteenForm.sortOrder" :min="0" style="width:100%"/></el-form-item><el-form-item label="启用状态"><el-switch v-model="canteenForm.status" :active-value="1" :inactive-value="0"/></el-form-item></el-form><template #footer><el-button @click="canteenDialog=false">取消</el-button><el-button type="primary" @click="saveCanteen">保存</el-button></template></el-dialog>

    <el-dialog v-model="passwordDialog" title="商户临时密码" width="460px" :close-on-click-modal="false"><el-alert title="该密码只显示本次，请复制后通过安全方式交给商户。商户首次登录后应立即修改密码。" type="warning" :closable="false" show-icon/><div class="admin-password-result"><span>{{passwordOwner}}</span><strong>{{temporaryPassword}}</strong><el-button type="primary" :icon="CopyDocument" @click="copyPassword">复制密码</el-button></div><template #footer><el-button type="primary" @click="passwordDialog=false">我已记录</el-button></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { Clock, CopyDocument, Download, Edit, Filter, Key, Picture, Plus, RefreshLeft, Search, Shop } from '@element-plus/icons-vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import request from '@/utils/request';
import './admin.css';

const tab=ref('shops'),keyword=ref(''),canteenId=ref(),shops=ref<any[]>([]),canteens=ref<any[]>([]),page=ref(1),total=ref(0),loading=ref(false),saving=ref(false);
const shopDialog=ref(false),canteenDialog=ref(false),passwordDialog=ref(false),temporaryPassword=ref(''),passwordOwner=ref('');
const shopForm=reactive<any>({}),canteenForm=reactive<any>({});const firstHours=ref<any>([]),secondHours=ref<any>([]);const uploading=reactive({logo:false,cover:false});
const emptyShop=()=>({id:null,name:'',canteenId:null,contactPhone:'',address:'',logoImage:'',coverImage:'',displaySort:0,status:1,visible:1,shopMode:'fixed_dish',peakLimitEnabled:0,tasteSensitiveEnabled:0,weightPricePer500g:null,minimumOrderWeightG:0});
const loadCanteens=async()=>canteens.value=await request.get('/api/admin/canteens');
const loadShops=async()=>{loading.value=true;try{const response:any=await request.get('/api/admin/shops',{params:{page:page.value,pageSize:20,keyword:keyword.value||undefined,canteenId:canteenId.value}});shops.value=response.records;total.value=response.total}finally{loading.value=false}};
const searchShops=()=>{page.value=1;loadShops()};const resetShopFilter=()=>{keyword.value='';canteenId.value=undefined;searchShops()};
const openShopForm=(row?:any)=>{const source=row?{...row,canteenId:row.canteen_id,contactPhone:row.contact_phone,logoImage:row.logo_image,coverImage:row.cover_image,displaySort:row.display_sort,shopMode:row.shop_mode,peakLimitEnabled:row.peak_limit_enabled,tasteSensitiveEnabled:row.taste_sensitive_enabled,weightPricePer500g:row.weight_price_per_500g,minimumOrderWeightG:row.minimum_order_weight_g}:emptyShop();Object.assign(shopForm,emptyShop(),source);firstHours.value=[row?.open_time1||'08:00:00',row?.close_time1||'20:00:00'];secondHours.value=row?.open_time2&&row?.close_time2?[row.open_time2,row.close_time2]:[];shopDialog.value=true};
const uploadImage=async(options:any,type:'logo'|'cover')=>{uploading[type]=true;try{const form=new FormData();form.append('file',options.file);const response:any=await request.post('/api/admin/upload/shop-image',form,{params:{type},headers:{'Content-Type':'multipart/form-data'}});shopForm[type==='logo'?'logoImage':'coverImage']=response.url;ElMessage.success('图片上传成功')}finally{uploading[type]=false}};
const uploadLogo=(options:any)=>uploadImage(options,'logo');const uploadCover=(options:any)=>uploadImage(options,'cover');
const showPassword=(owner:string,password:string)=>{passwordOwner.value=owner;temporaryPassword.value=password;passwordDialog.value=true};
const saveShop=async()=>{if(!shopForm.name.trim())return ElMessage.warning('请输入商户名称');if(!shopForm.canteenId)return ElMessage.warning('请选择所属食堂');[shopForm.openTime1,shopForm.closeTime1]=firstHours.value||[];[shopForm.openTime2,shopForm.closeTime2]=secondHours.value?.length?secondHours.value:[null,null];saving.value=true;try{if(shopForm.id){await request.put(`/api/admin/shops/${shopForm.id}`,shopForm);ElMessage.success('商户资料已更新')}else{const response:any=await request.post('/api/admin/shops',shopForm);showPassword(shopForm.name,response.initialPassword)}shopDialog.value=false;loadShops()}finally{saving.value=false}};
const resetPassword=async(row:any)=>{const{value}=await ElMessageBox.prompt('请输入重置原因','重置商户密码',{inputPlaceholder:'例如：商户忘记密码',inputValidator:value=>!!value?.trim()||'原因不能为空',type:'warning'});const response:any=await request.put(`/api/admin/shops/${row.id}/reset-password`,{reason:value});showPassword(row.name,response.temporaryPassword)};
const copyPassword=async()=>{try{await navigator.clipboard.writeText(temporaryPassword.value)}catch{const input=document.createElement('textarea');input.value=temporaryPassword.value;document.body.appendChild(input);input.select();document.execCommand('copy');input.remove()}ElMessage.success('密码已复制')};
const editCanteen=(row?:any)=>{Object.assign(canteenForm,row||{id:null,name:'',sortOrder:0,status:1});canteenDialog.value=true};
const saveCanteen=async()=>{if(!canteenForm.name?.trim())return ElMessage.warning('请输入食堂名称');if(canteenForm.id)await request.put(`/api/admin/canteens/${canteenForm.id}`,canteenForm);else await request.post('/api/admin/canteens',canteenForm);ElMessage.success('食堂已保存');canteenDialog.value=false;await Promise.all([loadCanteens(),loadShops()])};
const exportCsv=()=>fetch('/api/admin/export/shops',{headers:{Authorization:`Bearer ${localStorage.getItem('token')}`}}).then(response=>response.blob()).then(blob=>{const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='shops.csv';link.click();URL.revokeObjectURL(link.href)});
onMounted(()=>{loadCanteens();loadShops()});
</script>
