<template>
  <div class="admin-page admin-users">
    <div class="admin-page__header"><div><h2>用户管理</h2><p class="admin-page__description">查看用户活跃情况、历史订单和违规记录</p></div><el-button :icon="Download" @click="exportCsv">导出 CSV</el-button></div>
    <div class="admin-summary-strip admin-summary-strip--four"><div v-for="item in summaryItems" :key="item.label" class="admin-summary-item" :class="`admin-summary-item--${item.tone}`"><span class="admin-summary-item__icon"><el-icon><component :is="item.icon"/></el-icon></span><div><span>{{item.label}}</span><strong>{{item.value}}</strong></div></div></div>
    <div class="admin-users__top-grid">
      <section class="admin-filter-panel"><div class="admin-filter-panel__top"><div class="admin-filter-panel__title"><el-icon><Filter/></el-icon>筛选用户</div><el-button link :icon="RefreshLeft" @click="resetFilters">重置</el-button></div><div class="admin-filter-grid"><label><span>用户搜索</span><el-input v-model="keyword" placeholder="用户 ID、姓名或手机号" clearable @keyup.enter="search"/></label><label><span>处罚状态</span><el-select v-model="penalty" clearable placeholder="全部状态"><el-option v-for="item in penalties" :key="item.value" :label="item.label" :value="item.value"/></el-select></label><div class="admin-filter-panel__inline-action"><el-button type="primary" :icon="Search" @click="search">查询用户</el-button></div></div></section>
      <section class="admin-panel admin-top-users"><div class="admin-panel-toolbar"><div><strong>高频用户</strong><span>按累计下单次数排序</span></div><el-icon><Trophy/></el-icon></div><div class="admin-top-users__list"><div v-for="(user,index) in summary.topUsers||[]" :key="user.id"><b>{{Number(index)+1}}</b><span><strong>{{user.name||`用户 ${user.id}`}}</strong><small>{{user.phone||'未绑定手机号'}}</small></span><em>{{user.orderCount}} 单</em></div><div v-if="!summary.topUsers?.length" class="admin-empty admin-empty--compact">暂无排行数据</div></div></section>
    </div>
    <div class="admin-panel admin-table-panel"><el-table :data="records" v-loading="loading"><el-table-column label="用户" min-width="180"><template #default="scope"><div class="admin-user-cell"><span>{{String(scope.row.name||'用').slice(0,1)}}</span><div><strong>{{scope.row.name||'未实名用户'}}</strong><small>ID {{scope.row.id}}</small></div></div></template></el-table-column><el-table-column prop="phone" label="手机号" width="140"><template #default="scope">{{scope.row.phone||'-'}}</template></el-table-column><el-table-column prop="order_count" label="订单数" width="100" sortable/><el-table-column label="累计消费" width="120"><template #default="scope"><span class="admin-money">¥{{money(scope.row.total_spent)}}</span></template></el-table-column><el-table-column prop="no_show_count" label="逃单次数" width="100"><template #default="scope"><span :class="{'admin-text-danger':scope.row.no_show_count>0}">{{scope.row.no_show_count||0}}</span></template></el-table-column><el-table-column label="处罚状态" width="125"><template #default="scope"><el-tag :type="penaltyType(scope.row.penalty_status)">{{penaltyLabel(scope.row.penalty_status)}}</el-tag></template></el-table-column><el-table-column prop="create_time" label="注册时间" width="170"/><el-table-column label="操作" width="175" fixed="right"><template #default="scope"><el-button link type="primary" :icon="Tickets" @click="openOrders(scope.row)">历史订单</el-button><el-button link type="danger" :icon="Warning" @click="openPenalty(scope.row)">处罚</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="page" :page-size="20" :total="total" layout="total,prev,pager,next" @current-change="load" class="admin-pagination"/></div>

    <el-drawer v-model="ordersDrawer" size="760px" destroy-on-close><template #header><div class="admin-drawer-title"><span class="admin-drawer-title__icon"><el-icon><Tickets/></el-icon></span><div><strong>用户历史订单</strong><small>{{current?.name||'未实名用户'}} · ID {{current?.id}}</small></div></div></template><div class="admin-user-order-summary"><span><small>累计订单</small><strong>{{current?.order_count||0}}</strong></span><span><small>累计消费</small><strong>¥{{money(current?.total_spent)}}</strong></span><span><small>逃单次数</small><strong class="admin-text-danger">{{current?.no_show_count||0}}</strong></span></div><div class="admin-panel admin-table-panel"><el-table :data="orders" v-loading="ordersLoading"><el-table-column prop="id" label="订单号" min-width="180"><template #default="scope"><span class="admin-order-id">{{scope.row.id}}</span></template></el-table-column><el-table-column prop="shop_name" label="商户" min-width="120"/><el-table-column label="状态" width="95"><template #default="scope"><el-tag :type="orderTagType(scope.row.status)">{{orderStatus(scope.row.status)}}</el-tag></template></el-table-column><el-table-column label="金额" width="100"><template #default="scope"><span class="admin-money">¥{{money(scope.row.total_amount)}}</span></template></el-table-column><el-table-column prop="create_time" label="下单时间" width="170"/></el-table><div v-if="!orders.length&&!ordersLoading" class="admin-empty">该用户暂无订单</div></div></el-drawer>

    <el-dialog v-model="penaltyDialog" title="用户处罚处理" width="520px" destroy-on-close><el-alert :title="`${current?.name||'用户'}（ID ${current?.id}）当前状态：${penaltyLabel(current?.penalty_status)}`" type="warning" :closable="false" show-icon/><el-form label-position="top" class="admin-dialog-form"><el-form-item label="处罚状态"><el-select v-model="form.status" style="width:100%"><el-option v-for="item in penalties" :key="item.value" :label="item.label" :value="item.value"/></el-select></el-form-item><el-form-item label="逃单次数"><el-input-number v-model="form.noShowCount" :min="0" style="width:100%"/></el-form-item><el-form-item label="处理原因"><el-input v-model="form.reason" type="textarea" :rows="4" maxlength="200" show-word-limit placeholder="请填写处罚或解除处罚的原因"/></el-form-item></el-form><template #footer><el-button @click="penaltyDialog=false">取消</el-button><el-button type="danger" @click="savePenalty">保存处理结果</el-button></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { CirclePlus, Download, Filter, RefreshLeft, Search, Tickets, Trophy, User, UserFilled, Warning } from '@element-plus/icons-vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import request from '@/utils/request';
import './admin.css';
const penalties=[{value:'normal',label:'正常'},{value:'blocked_3d',label:'限制 3 天'},{value:'blocked_7d',label:'限制 7 天'},{value:'blocked_30d',label:'限制 30 天'},{value:'frozen',label:'永久冻结'}];
const keyword=ref(''),penalty=ref(''),records=ref<any[]>([]),total=ref(0),page=ref(1),loading=ref(false),summary=ref<any>({});
const ordersDrawer=ref(false),penaltyDialog=ref(false),ordersLoading=ref(false),current=ref<any>(),orders=ref<any[]>([]);const form=reactive({status:'normal',noShowCount:0,reason:''});
const money=(value:any)=>Number(value||0).toFixed(2);const penaltyLabel=(value:string)=>penalties.find(item=>item.value===value)?.label||'正常';const penaltyType=(value:string)=>!value||value==='normal'?'success':value==='frozen'?'danger':'warning';
const orderStatus=(value:string)=>({making:'制作中',pending:'待取餐',completed:'已完成',cancelled:'已取消'}[value]||value);const orderTagType=(value:string)=>value==='completed'?'success':value==='cancelled'?'danger':value==='pending'?'warning':'primary';
const summaryItems=computed(()=>[{label:'用户总量',value:summary.value.totalUsers||0,tone:'blue',icon:User},{label:'近 30 天新增',value:summary.value.newUsers30d||0,tone:'green',icon:CirclePlus},{label:'下过单用户',value:summary.value.orderedUsers||0,tone:'violet',icon:UserFilled},{label:'当前受限用户',value:summary.value.restrictedUsers||0,tone:'red',icon:Warning}]);
const load=async()=>{loading.value=true;try{const response:any=await request.get('/api/admin/users',{params:{page:page.value,pageSize:20,keyword:keyword.value||undefined,penaltyStatus:penalty.value||undefined}});records.value=response.records;total.value=response.total}finally{loading.value=false}};const loadSummary=async()=>summary.value=await request.get('/api/admin/users/summary');
const search=()=>{page.value=1;load()};const resetFilters=()=>{keyword.value='';penalty.value='';search()};
const openOrders=async(row:any)=>{current.value=row;ordersDrawer.value=true;ordersLoading.value=true;try{orders.value=await request.get(`/api/admin/users/${row.id}/orders`)}finally{ordersLoading.value=false}};
const openPenalty=(row:any)=>{current.value=row;form.status=row.penalty_status||'normal';form.noShowCount=row.no_show_count||0;form.reason='';penaltyDialog.value=true};
const savePenalty=async()=>{if(!form.reason.trim())return ElMessage.warning('请填写处理原因');await ElMessageBox.confirm('确认保存该用户的处罚状态？','确认操作',{type:'warning'});await request.put(`/api/admin/users/${current.value.id}/penalty`,form);ElMessage.success('用户处理结果已保存');penaltyDialog.value=false;await Promise.all([load(),loadSummary()])};
const exportCsv=()=>fetch('/api/admin/export/users',{headers:{Authorization:`Bearer ${localStorage.getItem('token')}`}}).then(response=>response.blob()).then(blob=>{const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='users.csv';link.click();URL.revokeObjectURL(link.href)});
onMounted(()=>{load();loadSummary()});
</script>
