<template>
  <div class="admin-page admin-config" v-loading="loading">
    <div class="admin-page__header"><div><h2>运营配置</h2><p class="admin-page__description">查看并维护平台预约规则与抽奖活动参数</p></div><div class="admin-header-actions"><template v-if="editing"><el-button @click="cancelEdit">取消编辑</el-button><el-button type="primary" :icon="Check" :loading="saving" @click="saveAll">保存全部配置</el-button></template><el-button v-else type="primary" :icon="Edit" @click="startEdit">进入编辑模式</el-button></div></div>
    <el-alert v-if="editing" title="当前处于编辑模式，修改仅在点击“保存全部配置”后生效。" type="warning" :closable="false" show-icon class="admin-config__alert"/>
    <div class="admin-config__grid">
      <section class="admin-panel admin-config-card">
        <div class="admin-config-card__header"><span class="admin-config-card__icon admin-config-card__icon--blue"><el-icon><Clock/></el-icon></span><div><h3>预约规则</h3><p>控制普通时段与高峰时段的最短预约时间</p></div><el-tag :type="reservation.workdayOnly?'primary':'info'">{{reservation.workdayOnly?'仅工作日':'每天生效'}}</el-tag></div>
        <template v-if="!editing"><div class="admin-config-values"><div><span>非高峰最短预约</span><strong>{{reservation.offPeakMinMinutes??'-'}} 分钟</strong></div><div><span>高峰最短预约</span><strong>{{reservation.peakMinMinutes??'-'}} 分钟</strong></div><div><span>午间高峰</span><strong>{{timeRange(reservation.lunchPeakStart,reservation.lunchPeakEnd)}}</strong></div><div><span>晚间高峰</span><strong>{{timeRange(reservation.dinnerPeakStart,reservation.dinnerPeakEnd)}}</strong></div><div><span>生效日期</span><strong>{{reservation.workdayOnly?'周一至周五':'每一天'}}</strong></div><div><span>最后更新</span><strong>{{reservation.updateTime||'-'}}</strong></div></div></template>
        <el-form v-else label-position="top" class="admin-config-form"><div class="admin-form-grid"><el-form-item label="非高峰最短预约"><el-input-number v-model="reservation.offPeakMinMinutes" :min="0" :max="180" style="width:100%"/><small>用户至少提前多少分钟下单</small></el-form-item><el-form-item label="高峰最短预约"><el-input-number v-model="reservation.peakMinMinutes" :min="0" :max="180" style="width:100%"/><small>午晚高峰期间使用此时间</small></el-form-item><el-form-item label="午间高峰"><el-time-picker v-model="lunch" is-range value-format="HH:mm:ss" range-separator="至" start-placeholder="开始" end-placeholder="结束" style="width:100%"/></el-form-item><el-form-item label="晚间高峰"><el-time-picker v-model="dinner" is-range value-format="HH:mm:ss" range-separator="至" start-placeholder="开始" end-placeholder="结束" style="width:100%"/></el-form-item></div><div class="admin-switch-list"><label><div><strong>仅工作日生效</strong><span>周末将按非高峰预约逻辑处理</span></div><el-switch v-model="reservation.workdayOnly" :active-value="1" :inactive-value="0"/></label></div></el-form>
      </section>
      <section class="admin-panel admin-config-card">
        <div class="admin-config-card__header"><span class="admin-config-card__icon admin-config-card__icon--orange"><el-icon><Present/></el-icon></span><div><h3>抽奖活动</h3><p>控制每日预约抽奖的参与时间和兑奖信息</p></div><el-tag :type="lucky.status?'success':'info'">{{lucky.status?'活动中':'已停用'}}</el-tag></div>
        <template v-if="!editing"><div class="admin-config-values"><div class="admin-config-values__full"><span>活动名称</span><strong>{{lucky.activityName||'未设置'}}</strong></div><div><span>预约时间</span><strong>{{timeRange(lucky.reserveStartTime,lucky.reserveEndTime)}}</strong></div><div><span>开奖时间</span><strong>{{shortTime(lucky.drawTime)}}</strong></div><div><span>奖品类型</span><strong>{{lucky.prizeType==='cash'?'现金':'其他'}}</strong></div><div><span>单份奖品</span><strong>¥{{money(lucky.prizeValue)}}</strong></div><div><span>每日中奖人数</span><strong>{{lucky.maxWinnersPerDay??'-'}} 人</strong></div><div><span>兑奖微信</span><strong>{{lucky.redeemWechat||'未设置'}}</strong></div><div class="admin-config-values__full"><span>活动说明</span><strong>{{lucky.description||'暂无说明'}}</strong></div></div></template>
        <el-form v-else label-position="top" class="admin-config-form"><div class="admin-form-grid"><el-form-item label="活动名称" class="admin-form-grid__full"><el-input v-model="lucky.activityName"/></el-form-item><el-form-item label="预约时间"><el-time-picker v-model="reserve" is-range value-format="HH:mm:ss" range-separator="至" start-placeholder="开始" end-placeholder="结束" style="width:100%"/></el-form-item><el-form-item label="开奖时间"><el-time-picker v-model="lucky.drawTime" value-format="HH:mm:ss" style="width:100%"/></el-form-item><el-form-item label="单份奖品金额"><el-input-number v-model="lucky.prizeValue" :min="0" :precision="2" style="width:100%"/></el-form-item><el-form-item label="每日中奖人数"><el-input-number v-model="lucky.maxWinnersPerDay" :min="1" style="width:100%"/></el-form-item><el-form-item label="兑奖微信"><el-input v-model="lucky.redeemWechat"/></el-form-item><el-form-item label="活动说明" class="admin-form-grid__full"><el-input v-model="lucky.description" type="textarea" :rows="3"/></el-form-item></div><div class="admin-switch-list"><label><div><strong>启用抽奖活动</strong><span>关闭后用户端不再开放参与入口</span></div><el-switch v-model="lucky.status" :active-value="1" :inactive-value="0"/></label></div></el-form>
      </section>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { Check, Clock, Edit, Present } from '@element-plus/icons-vue';
import { ElMessage } from 'element-plus';
import request from '@/utils/request';
import './admin.css';
const reservation=reactive<any>({}),lucky=reactive<any>({});const lunch=ref<any>([]),dinner=ref<any>([]),reserve=ref<any>([]);const editing=ref(false),loading=ref(false),saving=ref(false);let snapshot:any={};
const syncTimes=()=>{lunch.value=[reservation.lunchPeakStart,reservation.lunchPeakEnd];dinner.value=[reservation.dinnerPeakStart,reservation.dinnerPeakEnd];reserve.value=[lucky.reserveStartTime,lucky.reserveEndTime]};
const load=async()=>{loading.value=true;try{const response:any=await request.get('/api/admin/config');Object.keys(reservation).forEach(key=>delete reservation[key]);Object.keys(lucky).forEach(key=>delete lucky[key]);Object.assign(reservation,response.reservationRule||{});Object.assign(lucky,response.luckyDraw||{});syncTimes()}finally{loading.value=false}};
const startEdit=()=>{snapshot=JSON.parse(JSON.stringify({reservation,lucky}));syncTimes();editing.value=true};
const cancelEdit=()=>{Object.assign(reservation,snapshot.reservation||{});Object.assign(lucky,snapshot.lucky||{});syncTimes();editing.value=false};
const saveAll=async()=>{if(!lunch.value?.length||!dinner.value?.length)return ElMessage.warning('请完整设置午间和晚间高峰');if(!reserve.value?.length||!lucky.drawTime)return ElMessage.warning('请完整设置抽奖预约和开奖时间');[reservation.lunchPeakStart,reservation.lunchPeakEnd]=lunch.value;[reservation.dinnerPeakStart,reservation.dinnerPeakEnd]=dinner.value;[lucky.reserveStartTime,lucky.reserveEndTime]=reserve.value;lucky.prizeType=lucky.prizeType||'cash';saving.value=true;try{await Promise.all([request.put('/api/admin/config/reservation',reservation),request.put('/api/admin/config/lucky-draw',lucky)]);ElMessage.success('运营配置已保存');editing.value=false;await load()}finally{saving.value=false}};
const shortTime=(value:string)=>value?String(value).slice(0,5):'-';const timeRange=(start:string,end:string)=>start&&end?`${shortTime(start)} - ${shortTime(end)}`:'未设置';const money=(value:any)=>Number(value||0).toFixed(2);
onMounted(load);
</script>
